### ISSUE TITLE
Executable 'ffprobe' not found

### ISSUE THREAD

**Issue by gormir** [sdbds/audiocraft-webui#5]
After pressing submit , every seem to be working fine and at the end of the prosess after reaching the 100% i get the following error:

new batch 1 ['metal piano'] [None]
Make a video took 0.4948465824127197
batch finished 1 15.496354341506958
Traceback (most recent call last):
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\ffmpy.py", line 93, in run
    self.process = subprocess.Popen(
  File "H:\Python3.10.8\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\Python3.10.8\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\components.py", line 2190, in postprocess
    processed_files = (self._format_video(y), None)
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\components.py", line 2237, in _format_video
    and not processing_utils.video_is_playable(video)
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\gradio\processing_utils.py", line 498, in video_is_playable
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "L:\AIMusic\audiocraft-webui\venv\lib\site-packages\ffmpy.py", line 98, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found

i havent been able to find a working solution for this problem ( i do have ffmpeg installed ) .

**Comment by sdbds** [comment]
You need to add an environment variable about ffmpeg.i will add it in Readme

**Comment by sdbds** [comment]
add it in readme,maybe i wll add it in script in future
